services:
  portfolio-backend:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    networks:
      - web

networks:
  web:
    name: pangolin
    external: true